#!/usr/bin/env python3
"""Run the Xiaohongshu Feishu delivery workflow in a target workspace.

This is the public skill entrypoint. It does not contain business content or
draw image cards itself; image cards must be generated by an image skill/model
before the packaging and Feishu delivery steps run.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from contextlib import contextmanager
from pathlib import Path


BUILD_REQUIRED_FILES = [
    # Files required for local-only, dry-run, and send modes.
    "asset-generation/content_spec.json",
    "asset-generation/write_copy_deepseek.py",
    "asset-generation/write_image_prompts_deepseek.py",
    "asset-generation/generate_current_assets.py",
    "publish-mainline/build_manual_publish_package.py",
    "publish-mainline/preflight.py",
    "feishu-delivery/build_delivery_card.py",
    "feishu-delivery/send_delivery_card.py",
]

CHECK_REQUIRED_FILES = [
    # Minimal file required when only checking Feishu credentials.
    "feishu-delivery/check_feishu_ready.py",
]

STARTUP_REQUIRED_FILES = [
    # Minimal file required when installing startup health checks.
    "feishu-delivery/install_startup_check.py",
]

PENDING_SENDER_REQUIRED_FILES = [
    "feishu-delivery/send_pending_delivery.py",
    "feishu-delivery/install_pending_sender.py",
]

DEEPSEEK_WRITER_REQUIRED_FILES = [
    "asset-generation/run_deepseek_writers.py",
    "asset-generation/install_deepseek_writer_task.py",
    "asset-generation/write_copy_deepseek.py",
    "asset-generation/write_image_prompts_deepseek.py",
]

AUTOMATION_LOCK_REQUIRED_FILES = [
    "automation-lock/automation_lock.py",
]

DOCTOR_REQUIRED_FILES = [
    # Read-only workspace diagnostics.
    "diagnostics/doctor.py",
]

HISTORY_REQUIRED_FILES = [
    # Sent-post history inspection and duplicate detection.
    "content-history/check_history.py",
    "content-history/history_utils.py",
]

LOCK_TTL_SECONDS = 2 * 60 * 60


def resolve_workspace(raw: str) -> Path:
    workspace = Path(raw).expanduser().resolve()
    if not workspace.exists():
        raise FileNotFoundError(f"workspace does not exist: {workspace}")
    if not workspace.is_dir():
        raise NotADirectoryError(f"workspace is not a directory: {workspace}")
    return workspace


def require_files(workspace: Path, required_files: list[str]) -> None:
    """Fail early with a clear message if the workspace is incomplete."""
    missing = [path for path in required_files if not (workspace / path).exists()]
    if missing:
        raise FileNotFoundError("workspace is missing required files: " + ", ".join(missing))


def run_step(workspace: Path, name: str, args: list[str]) -> None:
    """Run one workflow step inside the target workspace."""
    print(f"\n== {name} ==")
    completed = subprocess.run(
        args,
        cwd=workspace,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if completed.returncode != 0:
        raise SystemExit(completed.returncode)


@contextmanager
def workflow_lock(workspace: Path):
    """Prevent two runs from writing the same output files at the same time."""
    lock_path = workspace / ".xhs_delivery.lock"
    if lock_path.exists():
        age = time.time() - lock_path.stat().st_mtime
        if age > LOCK_TTL_SECONDS:
            lock_path.unlink()
        else:
            raise SystemExit(
                f"workflow already running or lock exists: {lock_path}. "
                "If no workflow is running, delete this lock file and retry."
            )
    fd = os.open(str(lock_path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
    try:
        os.write(fd, f"pid={os.getpid()}\n".encode("utf-8"))
    finally:
        os.close(fd)
    try:
        yield
    finally:
        if lock_path.exists():
            lock_path.unlink()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run XHS Feishu delivery workflow")
    parser.add_argument(
        "--workspace",
        required=True,
        help="Path to a workspace containing asset-generation, image-generation, publish-mainline, and feishu-delivery.",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--init-workspace", action="store_true", help="Create the workspace from this skill's bundled template")
    mode.add_argument("--check-feishu", action="store_true", help="Check Feishu credentials without building or sending")
    mode.add_argument("--doctor", action="store_true", help="Run read-only workspace diagnostics and write a doctor report")
    mode.add_argument("--history", action="store_true", help="List recent sent Xiaohongshu delivery history")
    mode.add_argument("--check-history", action="store_true", help="Check current content_spec.json against sent history")
    mode.add_argument("--install-startup-check", action="store_true", help="Install a Windows logon Feishu health check")
    mode.add_argument("--install-system-startup-check", action="store_true", help="Install a Windows startup health check; requires administrator")
    mode.add_argument("--uninstall-startup-check", action="store_true", help="Remove the Windows logon Feishu health check")
    mode.add_argument("--install-pending-sender", action="store_true", help="Install the local Windows pending-send task")
    mode.add_argument("--uninstall-pending-sender", action="store_true", help="Remove the local Windows pending-send task")
    mode.add_argument("--pending-sender-status", action="store_true", help="Show pending-send task and queue status")
    mode.add_argument("--trigger-pending-sender", action="store_true", help="Trigger the local Windows pending-send task")
    mode.add_argument("--install-deepseek-writers", action="store_true", help="Install the local Windows DeepSeek writer task")
    mode.add_argument("--uninstall-deepseek-writers", action="store_true", help="Remove the local Windows DeepSeek writer task")
    mode.add_argument("--deepseek-writers-status", action="store_true", help="Show DeepSeek writer task and result status")
    mode.add_argument("--trigger-deepseek-writers", action="store_true", help="Trigger the local Windows DeepSeek writer task")
    mode.add_argument("--run-deepseek-writers", action="store_true", help="Run DeepSeek copy and image prompt writers")
    mode.add_argument("--automation-lock-status", action="store_true", help="Show the workspace automation lock status")
    mode.add_argument("--acquire-automation-lock", action="store_true", help="Acquire the workspace automation lock")
    mode.add_argument("--release-automation-lock", action="store_true", help="Release the workspace automation lock")
    mode.add_argument("--local-only", action="store_true", help="Build and validate without Feishu credentials")
    mode.add_argument("--dry-run", action="store_true", help="Build and validate Feishu credentials")
    mode.add_argument("--send", action="store_true", help="Build and send the Feishu delivery card")
    mode.add_argument("--queue-send", action="store_true", help="Queue the current validated package for the local sender")
    mode.add_argument("--send-pending", action="store_true", help="Send a queued package from the local pending sender")
    parser.add_argument("--trigger-local-sender", action="store_true", help="With --queue-send, trigger the Windows pending-send task")
    return parser


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv)
    if args.trigger_local_sender and not args.queue_send:
        raise SystemExit("--trigger-local-sender can only be used with --queue-send")
    if args.init_workspace:
        run_step(
            Path(__file__).resolve().parents[1],
            "init_workspace",
            [sys.executable, ".\\scripts\\init_workspace.py", "--workspace", args.workspace],
        )
        return 0

    workspace = resolve_workspace(args.workspace)
    if args.check_feishu:
        require_files(workspace, CHECK_REQUIRED_FILES)
        run_step(workspace, "check_feishu_ready", [sys.executable, ".\\feishu-delivery\\check_feishu_ready.py"])
        return 0
    if args.doctor:
        require_files(workspace, DOCTOR_REQUIRED_FILES)
        run_step(workspace, "doctor", [sys.executable, ".\\diagnostics\\doctor.py"])
        return 0
    if args.history:
        require_files(workspace, HISTORY_REQUIRED_FILES)
        run_step(workspace, "history", [sys.executable, ".\\content-history\\check_history.py", "--list"])
        return 0
    if args.check_history:
        require_files(workspace, HISTORY_REQUIRED_FILES)
        run_step(workspace, "check_history", [sys.executable, ".\\content-history\\check_history.py", "--check-current"])
        return 0
    if args.install_startup_check:
        require_files(workspace, STARTUP_REQUIRED_FILES)
        run_step(workspace, "install_startup_check", [sys.executable, ".\\feishu-delivery\\install_startup_check.py"])
        return 0
    if args.install_system_startup_check:
        require_files(workspace, STARTUP_REQUIRED_FILES)
        run_step(workspace, "install_system_startup_check", [sys.executable, ".\\feishu-delivery\\install_startup_check.py", "--system"])
        return 0
    if args.uninstall_startup_check:
        require_files(workspace, STARTUP_REQUIRED_FILES)
        run_step(workspace, "uninstall_startup_check", [sys.executable, ".\\feishu-delivery\\install_startup_check.py", "--uninstall"])
        return 0
    if args.install_pending_sender:
        require_files(workspace, PENDING_SENDER_REQUIRED_FILES)
        run_step(workspace, "install_pending_sender", [sys.executable, ".\\feishu-delivery\\install_pending_sender.py", "--install"])
        return 0
    if args.uninstall_pending_sender:
        require_files(workspace, PENDING_SENDER_REQUIRED_FILES)
        run_step(workspace, "uninstall_pending_sender", [sys.executable, ".\\feishu-delivery\\install_pending_sender.py", "--uninstall"])
        return 0
    if args.pending_sender_status:
        require_files(workspace, PENDING_SENDER_REQUIRED_FILES)
        run_step(workspace, "pending_sender_status", [sys.executable, ".\\feishu-delivery\\send_pending_delivery.py", "--status"])
        run_step(workspace, "pending_sender_task_status", [sys.executable, ".\\feishu-delivery\\install_pending_sender.py", "--status"])
        return 0
    if args.trigger_pending_sender:
        require_files(workspace, PENDING_SENDER_REQUIRED_FILES)
        run_step(workspace, "trigger_pending_sender", [sys.executable, ".\\feishu-delivery\\install_pending_sender.py", "--run-now"])
        return 0
    if args.install_deepseek_writers:
        require_files(workspace, DEEPSEEK_WRITER_REQUIRED_FILES)
        run_step(workspace, "install_deepseek_writers", [sys.executable, ".\\asset-generation\\install_deepseek_writer_task.py", "--install"])
        return 0
    if args.uninstall_deepseek_writers:
        require_files(workspace, DEEPSEEK_WRITER_REQUIRED_FILES)
        run_step(workspace, "uninstall_deepseek_writers", [sys.executable, ".\\asset-generation\\install_deepseek_writer_task.py", "--uninstall"])
        return 0
    if args.deepseek_writers_status:
        require_files(workspace, DEEPSEEK_WRITER_REQUIRED_FILES)
        run_step(workspace, "deepseek_writers_status", [sys.executable, ".\\asset-generation\\run_deepseek_writers.py", "--status"])
        run_step(workspace, "deepseek_writer_task_status", [sys.executable, ".\\asset-generation\\install_deepseek_writer_task.py", "--status"])
        return 0
    if args.trigger_deepseek_writers:
        require_files(workspace, DEEPSEEK_WRITER_REQUIRED_FILES)
        run_step(workspace, "trigger_deepseek_writers", [sys.executable, ".\\asset-generation\\install_deepseek_writer_task.py", "--run-now"])
        return 0
    if args.run_deepseek_writers:
        require_files(workspace, DEEPSEEK_WRITER_REQUIRED_FILES)
        run_step(workspace, "run_deepseek_writers", [sys.executable, ".\\asset-generation\\run_deepseek_writers.py", "--run"])
        return 0
    if args.automation_lock_status:
        require_files(workspace, AUTOMATION_LOCK_REQUIRED_FILES)
        run_step(workspace, "automation_lock_status", [sys.executable, ".\\automation-lock\\automation_lock.py", "--status"])
        return 0
    if args.acquire_automation_lock:
        require_files(workspace, AUTOMATION_LOCK_REQUIRED_FILES)
        run_step(workspace, "acquire_automation_lock", [sys.executable, ".\\automation-lock\\automation_lock.py", "--acquire"])
        return 0
    if args.release_automation_lock:
        require_files(workspace, AUTOMATION_LOCK_REQUIRED_FILES)
        run_step(workspace, "release_automation_lock", [sys.executable, ".\\automation-lock\\automation_lock.py", "--release"])
        return 0
    if args.queue_send:
        require_files(workspace, BUILD_REQUIRED_FILES + PENDING_SENDER_REQUIRED_FILES)
        run_step(workspace, "queue_pending_send", [sys.executable, ".\\feishu-delivery\\send_pending_delivery.py", "--queue"])
        if args.trigger_local_sender:
            run_step(workspace, "trigger_pending_sender", [sys.executable, ".\\feishu-delivery\\install_pending_sender.py", "--run-now"])
        return 0
    if args.send_pending:
        require_files(workspace, BUILD_REQUIRED_FILES + PENDING_SENDER_REQUIRED_FILES)
        run_step(workspace, "send_pending_delivery", [sys.executable, ".\\feishu-delivery\\send_pending_delivery.py", "--send-pending"])
        return 0

    require_files(workspace, BUILD_REQUIRED_FILES + HISTORY_REQUIRED_FILES)
    send_mode = "--local-only"
    if args.dry_run:
        send_mode = "--dry-run"
    if args.send:
        send_mode = "--send"

    with workflow_lock(workspace):
        run_step(workspace, "generate_assets", [sys.executable, ".\\asset-generation\\generate_current_assets.py"])
        run_step(workspace, "build_manual_package", [sys.executable, ".\\publish-mainline\\build_manual_publish_package.py"])
        run_step(workspace, "preflight", [sys.executable, ".\\publish-mainline\\preflight.py"])
        run_step(workspace, "build_delivery_card", [sys.executable, ".\\feishu-delivery\\build_delivery_card.py"])
        run_step(workspace, "send_delivery_card", [sys.executable, ".\\feishu-delivery\\send_delivery_card.py", send_mode])
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
